apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: sensitive-environment-variables-with-argocd-secret-exclusion
spec:
  policyName: Sensitive Environment Variables with ArgoCD Secret Exclusion
  description: Alerts on deployments using environment variables with keys ''PASSWORD'' or ''SECRET'', while specifically excluding a known ArgoCD secret path. This policy aims to flag other sensitive secrets or passwords, but ignore the managed ArgoCD secret.
  rationale: Exposure of sensitive credentials via environment variables is a security risk. This policy aims to mitigate that risk while allowing a specific, known ArgoCD secret, which is presumed to be securely managed, to exist without triggering alerts.
  remediation: Review environment variables of violating deployments. Remove sensitive data like passwords or secrets. If a secret is necessary, ensure it''s mounted as a volume from a Kubernetes Secret and not exposed as an environment variable, or use appropriate secret management tools.
  categories:
    - Security Best Practices
  lifecycleStages:
    - DEPLOY
  eventSource: NOT_APPLICABLE
  severity: CRITICAL_SEVERITY
  policySections:
    - sectionName: Don't trigger on Argo Secrets
      policyGroups:
        - fieldName: Environment Variable
          booleanOperator: OR
          values:
            - value: =SECRET=/secret/data/app/argocd/secret$
    - sectionName: Trigger on other sensitive secrets
      policyGroups:
        - fieldName: Environment Variable
          booleanOperator: OR
          values:
            - value: =PASSWORD=.*
            - value: =SECRET=.*
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
